---
seed: 1984
data_path: /home/vladimir/workspace/evo970/data/kaggle_alaska_2
sync_bn: True
num_folds: 5
fold_id: 0
num_workers: 16
experiment_name: "2020-05-31a"

train_csv_logs: "train.csv"
val_csv_logs: "val.csv"

model:
  type: timm.create_model
  model_name: seresnext26tn_32x4d
  num_classes: 1
  pretrained: True

trainer:
  type: pytorch_lightning.Trainer
  early_stop_callback: False
  default_save_path: ./
  gpus: 2
  use_amp: True
  amp_level: O1
  max_epochs: 100
  distributed_backend: ddp
  num_sanity_val_steps: 2
  train_percent_check: 1
  val_percent_check: 1.0
  progress_bar_refresh_rate: 1
  benchmark: True
  precision: 16

scheduler:
  type: kaggle_alaska_2.schedulers.PolyLR
  max_iter: 100

train_parameters:
  batch_size: 24
  stratified: True

checkpoint_callback:
  type: pytorch_lightning.callbacks.ModelCheckpoint
  filepath: "2020-05-31a"
  monitor: val_loss
  verbose: True
  mode: min
  save_top_k: -1

val_parameters:
  batch_size: 48

test_parameters:
  batch_size: 12
  tta: d4

optimizer:
  type: torch.optim.SGD
  lr: 0.001
  weight_decay: 0.0001

loss:
  type: torch.nn.BCEWithLogitsLoss

train_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
#      - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
#        always_apply: false
#        p: 0.5
#      - __class_fullname__: albumentations.augmentations.transforms.RandomRotate90
#        always_apply: false
#        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.8479653533277325
          - 0.6896137811728085
          - 0.7924397729671702
        p: 1
        std:
          - 0.16774536877893925
          - 0.2740486792335106
          - 0.18297546821447516


val_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.8479653533277325
          - 0.6896137811728085
          - 0.7924397729671702
        p: 1
        std:
          - 0.16774536877893925
          - 0.2740486792335106
          - 0.18297546821447516

test_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.8479653533277325
          - 0.6896137811728085
          - 0.7924397729671702
        p: 1
        std:
          - 0.16774536877893925
          - 0.2740486792335106
          - 0.18297546821447516
