---
seed: 1984
data_path: /home/vladimir/workspace/evo970/data/kaggle_alaska_2
sync_bn: True
num_folds: 5
fold_id: 0
num_workers: 16
experiment_name: "2020-05-01"

model:
  type: timm.create_model
  model_name: resnet50
  num_classes: 2

trainer:
  type: pytorch_lightning.Trainer
  early_stop_callback: False
  default_save_path: ./
  gpus: 2
  use_amp: True
  amp_level: O1
  max_epochs: 100
  weights_summary: top
  distributed_backend: dp
  num_sanity_val_steps: 0
  train_percent_check: 1.0
  val_percent_check: 1.0
  progress_bar_refresh_rate: 1
  gradient_clip_val: 3
  benchmark: True

checkpoint_callback:
  type: pytorch_lightning.callbacks.ModelCheckpoint
  filepath: "2020-05-01"
  monitor: val_
  verbose: True
  mode: max
  save_top_k: 1

train_parameters:
  num_epochs: 100
  weight_decay: 1e-4
  batch_size: 128
  precision": 16

val_parameters:
  batch_size: 128

optimizer:
  type: iglovikov_helper_functions.dl.pytorch.optimizers.SGD_GC
  lr: 0.1

scheduler:
  type: kaggle_alaska_2.schedulers.PolyLR
  max_iter: 100

loss:
  type: torch.nn.CrossEntropyLoss

train_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.RandomCrop
        always_apply: false
        height: 128
        p: 1
        width: 128
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225

val_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.CenterCrop
        always_apply: false
        height: 512
        p: 1
        width: 512
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225
